# Generated by Django 5.2.4 on 2025-07-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('po', models.CharField(max_length=100)),
                ('qtd_pallet', models.IntegerField()),
                ('hall', models.CharField(max_length=100)),
                ('tipped', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('checker', models.CharField(blank=True, max_length=100)),
                ('feeder', models.CharField(blank=True, max_length=100)),
                ('putaway_driver', models.CharField(blank=True, max_length=100)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('bay1', models.CharField(blank=True, max_length=100)),
                ('bay2', models.CharField(blank=True, max_length=100)),
                ('bay3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
