# Generated by Django 5.2.4 on 2025-07-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_checker_alter_appointment_checker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='bay2',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='bay3',
        ),
    ]
