# Generated by Django 5.2.4 on 2025-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_bay2_remove_appointment_bay3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='feeder',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='putaway_driver',
        ),
    ]
