# Generated by Django 5.2.4 on 2025-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_feeder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_load',
            field=models.CharField(choices=[('on time', 'On Time'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='on time', max_length=20),
        ),
    ]
