# Generated by Django 5.2.4 on 2025-08-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_status_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status_load',
            field=models.CharField(choices=[('on time', 'On Time'), ('canceled', 'Canceled'), ('rescheduled', 'Rescheduled'), ('no show up', 'No Show up')], default='on time', max_length=20),
        ),
    ]
